### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by crypt0rr**
Updated `README.md` to reflect latest services.

### CODE REVIEW

**Review by jackspiering — DISMISSED** [review]
qBittorrent is not in correct alphabetical order, please fix.

**Comment by crypt0rr** [comment]
> qBittorrent is not in correct alphabetical order, please fix.

My Alphabetical order has PQR etc. yours different? Huh

**Comment by jackspiering** [comment]
I clearly dont know the alphabet > qBittorrent is not in correct alphabetical order, please fix.

**Review by jackspiering — APPROVED** [review]
Thoroughly checked on tiny mistakes

**Comment by crypt0rr** [comment]
Fixed pipeline

**Pull request merged**
